// <auto-generated />
using Khala.FakeDomain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Khala.FakeDomain.Migrations
{
    [DbContext(typeof(FakeProcessManagerDbContext))]
    partial class FakeProcessManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Khala.FakeDomain.FakeProcessManager", b =>
                {
                    b.Property<long>("SequenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AggregateId");

                    b.Property<Guid>("Id");

                    b.Property<string>("StatusValue");

                    b.HasKey("SequenceId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("FakeProcessManagers");
                });

            modelBuilder.Entity("Khala.Processes.Sql.PendingCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandJson")
                        .IsRequired();

                    b.Property<string>("Contributor");

                    b.Property<Guid?>("CorrelationId");

                    b.Property<Guid>("MessageId");

                    b.Property<string>("OperationId");

                    b.Property<Guid>("ProcessManagerId");

                    b.Property<string>("ProcessManagerType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessManagerId");

                    b.ToTable("PendingCommands");
                });

            modelBuilder.Entity("Khala.Processes.Sql.PendingScheduledCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandJson")
                        .IsRequired();

                    b.Property<string>("Contributor");

                    b.Property<Guid?>("CorrelationId");

                    b.Property<Guid>("MessageId");

                    b.Property<string>("OperationId");

                    b.Property<Guid>("ProcessManagerId");

                    b.Property<string>("ProcessManagerType")
                        .IsRequired();

                    b.Property<DateTime>("ScheduledTimeUtc");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessManagerId");

                    b.ToTable("PendingScheduledCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
